[book]
title = "1148 Code Guide and Quick Reference"
authors = ["YariMil (original)", "maxwaldman8 (original)", "Garret Morberg-Nguyen (maintainer)"]
language = "en"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["theme/1148.css"]
git-repository-url = "https://github.com/Harvard-Westlake-Robotics/Code-Guide-Quick-Reference"
edit-url-template = "https://github.com/Harvard-Westlake-Robotics/Code-Guide-Quick-Reference/edit/main/{path}"
site-url = "https://harvard-westlake-robotics.github.io/Code-Guide-Quick-Reference/"
